name = "EffectiveRelativisticFreedom"
uuid = "005c2b06-ab7a-47bc-8e90-0812660a6258"
authors = ["Quan-feng WU <32387646+Fenyutanchan@users.noreply.github.com>"]
version = "0.1.0"

[deps]
NaturalUnits = "61adfb09-12d1-4e3c-91b1-54bf68ca093d"
